apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.artifacts.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.artifacts.container.name }}
          image: {{ .Values.artifacts.container.image }}
          workingDir: {{ .Values.artifacts.container.workingDir }}
          volumeMounts:
             {{- range $k, $v := .Values.artifacts.container.volumeMounts }} 
             - {{ . | toYaml | indent 15 | trim }}
             {{- end }}              
          command:
            - /bin/bash
            - -c
            - |
              ./scripts/createGenesis.sh && 
              ./scripts/createChannel.sh
#              ./scripts/setAnchorPeer.sh
      restartPolicy: {{ .Values.artifacts.restartpolicy }}
      volumes:
        - name: {{ .Values.artifacts.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.artifacts.volume.claimname }}
