apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.peer0org3cli.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.peer0org3cli.labels }}
  template:
    metadata:
      labels:
        name: {{ .Values.peer0org3cli.labels }}
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: mypvc

      containers:
        - name: {{ .Values.peer0org3cli.container.name }}
          stdin: true
          tty: true
          resources:
            limits:
              memory: "{{ .Values.peer0org3cli.container.limits.memory }}"
              cpu: "{{ .Values.peer0org3cli.container.limits.cpu }}"
            requests:
              memory: "{{ .Values.peer0org3cli.container.requests.memory }}"
              cpu: "{{ .Values.peer0org3cli.container.requests.cpu }}"
          image: {{ .Values.peer0org3cli.container.labels }}
          workingDir: {{ .Values.peer0org3cli.container.workingDir }}
          env:
            {{- range $k, $v := .Values.peer0org3cli.container.env }}
             - {{ . | toYaml | indent 15 | trim }}
            {{- end }} 

          volumeMounts:
            {{- range $k, $v := .Values.peer0org3cli.container.volumeMounts }}  
             - {{ . | toYaml | indent 15 | trim }}
            {{- end }} 
