apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.org2.service.name }}
  labels:
    app: {{ .Values.org2.service.labels }}
spec:
  type: {{ .Values.org2.service.type }}
  selector:
    app: {{ .Values.org2.service.labels }}
  ports:
    - protocol: {{ .Values.org2.service.ports.protocol }}
      targetPort: {{ .Values.org2.service.ports.targetport }}
      port: {{ .Values.org2.service.ports.port }}